apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp 
    spec:
      containers:
      - name: reactjs-server
        image: phongson92/portfolio-reactjs
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  selector:
    app: reactapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 
