apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  strategy: 
    type: Recreate #
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: reactapp 
    spec:
      nodeName: tlinkvn-2434-k8s-node3 #set default node to run deployment
      containers:
      - name: reactjs-server
        image: phongson92/portfolio-reactjs:67
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  selector:
    app: reactapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31111